title: Jekyll And Hide
author: Edu No Godz
email: edunogodz@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is for test on how to create a GitHubPages
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
